project:
  type: book
  output-dir: docs

book:
  title: "Notas del Curso de Fases Topológicas del PCF 2014"
  author: "Diego Bautista"
  date: "2/15/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



